#CREATE DATABASE AND TABLES
#DROP DATABASE HOGIP;
#CREATE DATABASE HOGIP;

USE HOGIP;

CREATE TABLE feature(
	ID INT AUTO_INCREMENT,
	CLASSIFIER VARCHAR(128),
	SIGNATURE LONGTEXT,	
	dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

DELIMITER //
CREATE PROCEDURE addFeature( 
	IN CLASSIFIER varchar(128), 
	IN SIGNATURE LONGTEXT
)
BEGIN
	INSERT INTO feature VALUES( ID, CLASSIFIER, SIGNATURE, NOW() ); 
END // 
DELIMITER ;
